#+TITLE: 企业过冬的策略——道法自然系列
#+DATE: 2013-11-19
#+SETUPFILE: ~/octopress/org-sty/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 评论
#+JEKYLL_TAGS: 金融危机 企业战略
#+JEKYLL_PUBLISHED: true

这篇文章写于2008年，当时也是金融危机最为严重的时候。现在重新发在octopress博客里。

自然界的动植物，在亿万年中进化里，形成了非常高的生存智慧，将自己的生存与环境融为一体，并且将自身的竞争能力行成记忆，通过基因固化下来，不断的演进。并且通过个体与生态环境的交互循环，演绎自然的神奇与智慧。
道法自然，我希望可以写成一个系列，主旨是通过对自然界各类现象的剖析，发现一点自然的智慧之光，以期待对于企业与组织战略发展的新的探索。

这个“冬天”并不好过，而且据来自各方面的信息判断，这个冬季可能要格外的漫长。如何成功“熬”过这个冬天，是大多数企业面临的难题。

与自然的冬天相比，经济的“冬天”只有百年的历史，而前者则有亿万年的历史。看看自然界生物亿万年进化积累的越冬“智慧”。同样是熊，一个是狗熊，一个是北极熊。由于过冬环境的不同，而形成了各有特色的过冬本领。看看这些，也许对我们在思考企业“过冬”的时候有所启迪。

* 储存越冬的脂肪

寒冷的冬季，没有足够的能量积蓄，就无法应对未知的未来。无论是狗熊还是北极熊，都为寒冷贮备了厚厚的脂肪。狗熊都有冬眠的习惯，东北叫做“蹲仓”。依靠消耗体内储存起来的脂肪，狗熊可以舒舒服服地睡上几个月。

企业雄厚的资本积累，可以建立起应对寒冬的第一道防线。多年积累下来的留存收益和现金，可以让企业在收入下滑、利润锐减的时间有更强的耐受力。而没有什么积累的企业，在信贷紧缩的时候，借贷无门，如果没有新的应对策略，那么生存的危机就很严峻了。这个时候，降低成本提高效率就是必然的选择了。

* 降低新陈代谢水平

狗熊选择“冬眠”，这种看似很简单的行为，实际上是内部整体的整体代谢水平的降低，而厚厚的脂肪和皮毛，也将热量的散发降低至最小。而远在北极的北极熊却并不冬眠，只在天气最坏的时候缩起脑袋睡上几个小时，身上厚厚的绒毛和体内几乎同样厚的脂肪层起到了极好的保温作用，任凭大雪纷飞，暴风肆虐。

面临经济危机，国内外企业纷纷采取各种方法节约开支。裁员、关闭分支机构、压缩开支，这是企业常见的做法。这些做法的初衷是希望在短暂的剧疼之后，为企业迎来春天做好了准备。就如同冬天之前，需要对树枝进行修剪一样，是为了来年成长的更为茂盛。

然而，在削减开支的里面，不能所有开支“一刀切”。对于企业的成本支出来讲，按照能否产生附加价值来区分，不能带来附加价值的成本是越少越好，而能带来附加价值的成本，在减少时就需要谨慎了。比如营销费用、研发费用，一刀切下来之后，造成的是竞争优势的下降。

其实更好的办法是寻找替代的办法。简单的例子，同样作为营销手段的广告和公关传播，尽管两者各有特长，但是根据多年来针对不同行业的分析，公关传播的AVEs（等值广告系数）系数为3~5之间，就是在相同的传播效果下，公关传播的成本是广告的1/3~1/5。

而从现状来看，国内只有较大的企业，主要是IT、汽车和快速消费品、奢侈品等行业对公关传播的认知较高，而其他行业和区域企业对于公关的认知和应用就少得多了。

* 重新审视食物定位

因为狗熊的冬天只有短短几个月，仅靠脂肪也可熬过，即便如此也有偶尔出来觅食的时候。而北极熊则是积年累月在冰天雪地里——脂肪能应一时之需，长久的生存还需要不断的能量补充。北极熊的主要是环海豹，而且海豹含有丰富的脂肪，正是北极熊所需要的。

对于企业来讲，渡过漫长的冬天，不仅需要有资本的积累，而且需要不断寻找现金和利润的来源。需要重新审视自己的产业环境，专注于有价值的客户群体。根据客户的回款情况、利润高低和成长潜力等为度，重新评估，区分重点。

比如投影机市场，往年是政府投资主导的教育、政府行业市场是市场主力，而今年，投资紧缩直接带来的是教育和政府市场的萎缩，而商务市场却保持了高速增长。一些对于市场敏感的企业提前作出反应，在产品、营销、渠道等及早做出调整，就在竞争中赢得先机。

 
* 出奇制胜敏捷反应

捕食时，北极熊通常都是站在其呼吸孔的下风，以免自己的气味将海豹吓跑。它们总是全神贯注，一动不动地耐心等上几个小时，海豹脑袋一露出来，便会闪电般地一掌拍下去，将其脑壳打碎，并且立刻咬住，使其不致沉下水去，然后再用尽全身力气，将其从几米深的冰洞里拖出，饱餐一顿。却能在海豹浮出水面的瞬间，闪电般准确出击，一连串准确的进攻之后成功的手，需要的是整体的反应和协调能力。

面临寒冬，如何保证企业的高效的协作水平是面临的难题，也是必须具备的能力。市场闪现的机会也许稍纵即逝。锁定目标市场之后，协调内外部的资源，同时能够在不为竞争对手所知的情况下，出奇制胜。所以在考虑如何精简机构、压缩成本的时候，要知道，提高企业的生存能力和获利能力才是根本。

* 结语

冬天来了，春天的希望就不远了。但是如果“冬天”很漫长，那么仅靠消耗积累的脂肪也许是远远不够的，必须从内部组织、竞争策略等方面快速“进化”才可能生存下来。

“熬”过冬天的过程也许不是令人愉快的体验，但是残酷的自然和竞争却并不在意，而成功也永远属于笑到最后的竞争者。
