#+TITLE: Banking 2.0 随想
#+DATE: 2011-07-08
#+SETUPFILE: ~/octopress/org-sty/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 评论 
#+JEKYLL_TAGS: 银行 金融 IT bank2.0 banking2.0
#+JEKYLL_PUBLISHED: true


写下题目，忽然觉得，把 Bank2.0 改为 banking2.0 也许有更充分的理由。因为比尔.盖茨曾说过:”Banking is necessary but banks are not”。虽然原话我们无从考证，不过很多东西却值得回味。

试想一下，如果银行管理者问一下自己如下几个问题：您的银行为未来十年用户的应用需求变化做好应对准备了吗？您的银行能够在未来十年继续保持领先地位吗？能够保持持久的竞争优势么？

即便是花旗也曾破产保护，而不可一世的雷曼也轰然倒下。面临不那么确定的未来，也许答案并不那么确定。达尔文在数百年前就竞争给出了答案，适者生存。这既是竞争的法则，也是策略的根本出发点。竞争优势本来就是超越竞争对手的更强的适应环境的能力。

历史证明，任何银行的长期成功都离不开新的经营理念、创新的产品和服务、与客户保持密切地关注。在过去的几十年里，银行不断采用新的技术，但技术本身并不能保证成本、 速度和便利等方面的优势。

如果银行不能迅速的适应客户需求的趋势，客户将很快将他们忽略掉。而更糟的是，新的技术的应用和普及速度，可能远超过我们的想象。从开始到大规模普及应用，电话用了 50 年，电视用了 22 年，互联网用了 7 年，而 ipod 只用了 3 年，facebook 则只花了 2 年时间。就像如果十年前，别人说起 QQ，并不会认为这是一家如何的公司，但是现在却是全球第三大网络公司之一。

有人曾预测，未来，银行服务就像自来水一样，可以随时方便取用。银行要在其 DNA 中培养积极和一致的客户体验，可以将它们转化为可信赖的顾问支持。而现在比以往任何时候都更加重要。
“未来的金融服务，可以在任何时间和在几乎任何设备上，将服务交付给客户。最具创意及迅速的银行将有机会接触到最丰富的信息和建立最亲密的客户关系。他们将会达成在未来世界的银行愿景：在客户想到之前，展示每个可能的服务机会给他。”某银行业人士认为。

SapientNitro 金融服务部副总裁 Alex Sion 说，“欢迎来到参与银行的时代。今天的客户需要掌握一系列的选择，其中包括分行的联系专员、网上和移动银行、交互式语音应答系统、自动柜员机、直接邮寄等。目前个人银行业服务模式正在发生动态的能量转变，现在的消费者掌握了主动权。”

而起着驱动作用的技术一方面是银行本身的技术，另一方面则是来自于影响用户的行为的技术，比如互联网、社交网络与移动上网等新的技术与应用。而在未来的十年中移动网络和社交网络在个人金融消费中扮演的作用将更加凸出。而新的技术应用与需求，将对现有的模式产生巨大的冲击——也许说是推动更加积极一些。

《BANK 2.0》的作者 Brett King 认为：“行为的迅速变化、渠道互动、模式、品牌资产和对客户服务的期望意味着银行需要围绕客户开展创新，开发周期以几天或几周度量，而不是数月或数年。这种顾客行为的变化也许才刚刚开始。”

Brett King 在其富有洞察力的书中提出，由消费行为主导的零售银行服务未来将经历三个阶段的演变（如下图）。而每个阶段都有其独立性，并有足够的能量改变游戏规则。而时至 2015 年左右，第三个阶段对于零售银行业的作用将更加彻底和不可逆。

第一阶段发生于互联网时代。虽然很多银行否认网络泡沫时，互联网永远改变了客户接触银行和账户金钱的方式。正如讨论客户行为的心理时看到的，这给他们以前并不是可用的操控和选择。突然，客户进入到一个新的时代，他们可以如愿的随时访问自己的账户。

随着网上银行功能改进，前往银行网点的驱动开始减少，以及客户开始把网络银行作为其与银行的日常交易的主要渠道。在短短的 10 年内，以往 50-­‐60%的交易是通过在网点柜面、ATM 机或现金和支票完成的，而现在 90%的交易通过互联网、 电话中心和 ATM 上完成的。

第二个阶段正此刻正在发生。智能设备或应用程序如 iPhone 手机和谷歌 Android 的广泛普及，极大促进了口袋银行或移动银行的发展进程。尽管有不少关于安全和屏幕或设备本身的限制，但事实是许多银行已经在移动领域积极布局。未来在手机上除了不能提取现金，可以做 ATM 上做的任何事情。

第三阶段是非物理现金阶段（no physical cash）。在这个阶段我们将广泛应用移动手机支付。近距离无线通信（NFC，Near Field Communication）的移动钱包和储值小额支付已经就绪，然而即将到来的变化会更大。当这些更改发生时，我们需要现金将迅速减少。如果大部分交易都是通过电子钱包或借记卡卡基于移动设备完成，而较大的交易都是以电子方式通过网上银行或手机银行。那还剩下什么？现金——也许需求就是微乎其微了。

事情发展之快，而你却不能等待。永远的跟随也许并不是一个好的策略。如果推迟三年再行动，那么意味着你又要落后一步。而落后一步，意味着，大部分的新鲜果子已经没有了！也许，最好的策略也许就是去做、尝试和实验。
