#+TITLE: 猎物 1：CEO 不见了
#+DATE: 2018-11-11
#+SETUPFILE: ~/mysite/ccb/source/org-sty/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 小说
#+JEKYLL_TAGS:
#+JEKYLL_PUBLISHED: true

早上上班开始，媒体的电话便不断进来。

有的要求采访 CEO，有的要求采访 CFO，有的则是探口风。

当然这些都需要应付。应付媒体，本维持良好的企业形象,身就是公关部的职责所在。而应
付的原则则是口径一致，没有问题，但是具体的信息暂时不能透露。因为现在企业是在封口
期，因为正在进行季度审计，在审计结果出来之前，不便公开详细的财务信息。

形势严峻，部门内部简单讨论了一下，情况汇报上去了，然而，没有回音。

不妙的是，从双总部的另一边，传来的信息是，老板们不见了！对，CEO 和董事长同时不见
了。对就是不见了！！谁也不知道哪里去了。就是 CEO 和董事长助理也不知道两位大仙去哪
里了。不知是不知道，还是知道了不说。程二是在几年后才知道当时二人去了那里的。

Fuck！程二嘴里说了一句。然后把手里的签字笔抛在桌子上。桌子上，是公司配的笔记本电
脑。

法务部那边发来了一个链接。内容是一份分析，遭遇过混水攻击的公司名单，只有一家幸免
的。而幸免的方案，说起来简单至极，发表声明，说之前的财务报告数字上犯了一个错误，
公司正在纠正。然后过了一段时间，发了一个修正之后的数字，财务没那么好看。股价跌落，
然后止跌，最后反弹。重要的是公司还活着。其他的，都退市，然后过了一段时间就消失了。
至于图片[fn:1]（以后待补）。

中午去餐厅吃饭，其实一点胃口都没有，但是还是要吃的。和同事一起坐下，吃了两口，手
机响了，是一个新锐的财经网站的编辑。接通电话，便讲便走出餐厅。该网站找了一个擅长
上市公司财务打假的专家，要在网上开一个公开的研讨，讨论研究公司的财报。

决不能让这个事情发酵，必须尽全力阻止这次网络研讨。

唾沫也快干了，从企业理念愿景，到战略、产品，客户案例到市场占有率，到老板的个人情
怀——虽然老板 TMD 不见了，从金融危机谈到阴谋论，国外对崛起的中国的险恶用心，从金融
风险谈到国家的金融技术安全，终于，那位编辑同意了，取消专题。

长长的舒了一口气，回餐厅把凉透的午餐吃完。

* Footnotes

[fn:1] 图片待补
